version: '3.8'
services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/news-aggregator
      - /news-aggregator/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true