const nytApiAuthors = [
  'By Amelia Nierenberg',
  'By David A. Fahrenthold, Aatish Bhatia, Margot Sanger-Katz, Emily Badger, Ethan Singer and Josh Katz',
  'By Ryan Mac',
  'By Jon Pareles',
  'By Benjamin Mueller',
  'By Constant Méheut',
  'By Natalie Kitroeff, Kashmir Hill, Nina Feldman, Sydney Harper, Shannon M. Lin, Mary Wilson, Brendan Klinkenberg, Michael Benoist, Diane Wong, Marion Lozano, Rowan Niemisto, Elisheba Ittoop, Pat McCusker and Chris Wood',
  'By Alexandra Stevenson',
  'By Chris Buckley and Amy Chang Chien',
  'By Brooke Harrington',
]

const guardianApiAuthors = [
  'Jordan Strauss',
  'Patrick Pleul',
  'Trevor Leighton',
  'Saul Loeb',
  'Benjamin Fanjoy',
  'Antonio Olmos',
  'Manuel Orbegozo',
  'Matthias Schräder',
  'Dado Ruvić',
  'Mike Stewart',
  'Brandon Bell',
  'Aaron Chown',
  'CandyRetriever',
  'Richard Baker',
  'Courtesy of Microsoft',
  'Yui Mok',
  'miniseries',
  'Samuel Gibbs',
  'Chip Somodevilla',
  'Andrew Harnik',
  'Kevin Lamarque',
  'Eoneren',
  'Richard Bradley',
  'David Ryder',
  'Fabio De Paola',
  'Oli Scarff',
  'Dominic Lipinski',
  'Liewig Christian',
  'Scott A Garfitt',
  'Wodthikorn Phutthasatchathum',
  'John G Mabanglo',
  'Benoît Tessier',
  'Cheney Orr',
  'Facebook',
  'Mohammed Badra',
  'Dimitris Legakis',
  'Brendan McDermid',
  'Linda Nylind',
  'Omar Marques',
  'Beata Zawrzel',
  'Artur Widak',
  'Helen Sessions',
  'Kevin Wurm',
  'Yves Herman',
  'Dpa Picture Alliance',
  'Thomas Fuller',
  'Bloomberg',
  'Mike Blake',
  'Independent Photo Agency Srl',
  'Andre Pain',
  'Christophe Gowans',
  'Imago',
  'Jessica Lee',
  'Vuk Valcic',
  'Theophile Bloudanis',
  'Ukrinform',
  'Faisal Bashir',
  'Mike Segar',
  'Jacob King',
  'Jakub Porzycki',
  'GK Images',
  'Andrew Brookes',
  'Martin Godwin',
  'Yuliya Taba',
  'Agatha Cantrill',
  'Justin Sullivan',
  'Anadolu',
]

const bbcApiAuthors = ['BBC News', 'Clive Myrie', 'Sophie Raworth', 'Katty Kay']

const newsApiAuthors = [
  'Andrew Liszewski',
  'Jess Weatherbed',
  'Billy Givens',
  'Ryan Christoffel',
  'Ran Melamed',
  'Jim Norman',
  'Lisa D. Sparks',
  'Kevin Tierney',
  'Ollie Reynolds',
  'Ben Lovejoy',
  'Tom Phillips',
  'Wesley Yin-Poole',
  'Anthony Cuthbertson',
  'Tim Hardwick',
  'Rick Kazmer',
  'kittypokemonsalot',
  'Damien Wilde',
  'Sammy Barker',
  'Theodore McKenzie',
  'Christian de Looper',
  'Ben Branch',
  'SamMobile, Asif Iqbal Shaik',
  'Jaron Schneider',
  'Jeremy Gray',
  'Dan Maloney',
  'Joe Rossignol',
  'Richard Devine',
  'Paul Tassi',
  'Adam Corsetti',
  'Mick Abrahamson',
  'Noah Hunter',
  'Sam Medley',
  'MattIsForReal',
  'Ben Schoon',
  'Abid Ahsan Shanto',
  'Gilbert Smith',
  'Marc Deschamps',
  'Williesha Morris | wmorris@al.com',
  'Matt Swayne',
  'Giovanni Colantonio',
  'Frank Landymore',
  'Mark Gurman',
  'Stephen Radochia',
  'Carly Caramanna',
  'Ewan Moore',
  'Lawrence Hodge',
  'Alyse Stanley',
  'ET Online',
]

const nytApiSources = [
  'The New York Times',
  'International Herald Tribune',
  'New York Times Blogs',
  'NYTimes.com',
  'The New York Times Magazine',
  'The New York Times Book Review',
  'Reuters',
  'Associated Press',
  'UPI',
  'Agence France-Presse',
  'Bloomberg',
  'ProPublica',
  'CNBC',
  'CNN',
  'BBC News',
  'NPR',
  'PBS NewsHour',
  'The Guardian',
  'The Washington Post',
  'The Wall Street Journal',
  'Time',
  'USA Today',
  'Newsweek',
  'Business Insider',
  'Politico',
  'The Atlantic',
  'The Economist',
  'Financial Times',
  'The Telegraph',
  'The Independent',
  'Ars Technica',
  'TechCrunch',
  'Mashable',
  'Vox',
  'BuzzFeed',
  'Engadget',
  'Wired',
  'The Verge',
  'National Geographic',
  'Scientific American',
  'Nature',
  'Medical News Today',
  'Forbes',
  'Fox News',
  'Al Jazeera English',
  'Sky News',
  'Sky Sports',
  'ESPN',
  'Fox Sports',
  'CBS News',
  'NBC News',
  'ABC News',
  'Huffington Post',
  'Salon',
  'Electrek',
  'Digital Trends',
  'SlashGear',
  'TechRadar',
  'ZDNet',
  "Barron's",
  'WSOC-TV',
  'WSOC-TV Charlotte',
  'Axios',
  'BBC Sport',
  'The Sun',
  'The Daily Mail',
  'The Mirror',
  'Metro',
  'Scientific American',
  'Popular Science',
  'Live Science',
  'Discover Magazine',
  'ScienceDaily',
  'Nature News',
  'Smithsonian Magazine',
  'Space.com',
  'New Scientist',
  'Astronomy Magazine',
  'MIT Technology Review',
  'Wired Science',
  'The Hollywood Reporter',
  'Variety',
  'Deadline',
  'Billboard',
  'Rolling Stone',
  'NME',
  'Vulture',
  'Entertainment Weekly',
  'People',
  'Vanity Fair',
  'GQ',
  'Esquire',
  "Men's Health",
  "Women's Health",
  'Health',
  'WebMD',
  'Psychology Today',
  'The Scientist',
  'New York Post',
  'The Toronto Star',
  'The Globe and Mail',
  'The Australian',
  'The Sydney Morning Herald',
  'South China Morning Post',
  'The Straits Times',
  'The Japan Times',
  'The Times of India',
]

const newsApiSources = [
  'ABC News',
  'Al Jazeera English',
  'Associated Press',
  "Barron's",
  'BBC News',
  'Bloomberg',
  'Business Insider',
  'BuzzFeed',
  'CBS News',
  'CNN',
  'CNET',
  'Electrek',
  'Engadget',
  'Financial Times',
  'Forbes',
  'Fox News',
  'Huffington Post',
  'Karen Martin',
  'Mashable',
  'Medical News Today',
  'National Geographic',
  'Nature',
  'NBC News',
  'New York Magazine',
  'NPR',
  'Politico',
  'Reuters',
  'Salon',
  'Scientific American',
  'TechCrunch',
  'The Guardian',
  'The Independent',
  'The New York Times',
  'The Telegraph',
  'The Times of India',
  'The Wall Street Journal',
  'The Washington Post',
  'Time',
  'TipRanks',
  'USA Today',
  'Vox',
  'Wired',
  'WSOC-TV',
  'WSOC-TV Charlotte',
  'Axios',
  'BBC Sport',
  'ESPN',
  'Fox Sports',
  'Sky News',
  'Sky Sports',
  'The Sun',
  'The Daily Mail',
  'The Mirror',
  'Metro',
  'The Verge',
  'Ars Technica',
  'Digital Trends',
  'SlashGear',
  'TechRadar',
  'ZDNet',
]

const guardianApiSources = [
  'Journalists and Reporters',
  'News Agencies',
  'Freelance Writers',
  'Public Records and Documents',
  'Interviews and Eyewitness Accounts',
  'Research and Studies',
  'User-Generated Content',
  'Press Releases',
  'Think Tanks and NGOs',
  'Scientific Journals',
  'Books and Literature',
  'Public Records and Databases',
  'Partnerships',
  'Opinion Pieces and Columns',
  'Data Journalism',
  'Crowdsourcing',
  'Foreign Correspondents',
  'Multimedia Content',
  'Investigative Reports',
  'Reuters',
  'Associated Press (AP)',
  'Agence France-Presse (AFP)',
  'Bloomberg',
  'Press Association (PA)',
  'Al Jazeera',
  'Thomson Reuters Foundation',
  'Xinhua News Agency',
  'TASS (Russian News Agency)',
  'Kyodo News',
  'The New York Times',
  'BBC News',
  'CNN',
  'Financial Times',
  'The Washington Post',
  'NPR (National Public Radio)',
  'The Independent',
  'The Economist',
  'VICE News',
  'Deutsche Welle (DW)',
  'South China Morning Post',
  'Le Monde',
  'El País',
  'HuffPost',
  'BuzzFeed News',
  'Politico',
  'The Wall Street Journal',
  'The Times',
  'The Telegraph',
  'Forbes',
  'TIME Magazine',
  'USA Today',
  'Los Angeles Times',
  'The Atlantic',
  'Slate',
  'New York Magazine',
  'The Nation',
  'Mother Jones',
  'ProPublica',
  'The Intercept',
  'CBC News',
  'CTV News',
  'ABC News',
  'Sky News',
  'Channel 4 News',
  'The Sydney Morning Herald',
  'Global Voices',
  'The Conversation',
  'Reporters Without Borders (RSF)',
  'Human Rights Watch',
  'Amnesty International',
  'Transparency International',
  'International Crisis Group',
  'Greenpeace',
  'World Health Organization (WHO)',
  'United Nations (UN)',
  'International Monetary Fund (IMF)',
  'World Bank',
  'OECD (Organization for Economic Co-operation and Development)',
  'Pew Research Center',
  'Gallup',
  'Ipsos',
  'YouGov',
  'Center for Disease Control and Prevention (CDC)',
  'NASA',
  'European Space Agency (ESA)',
  'International Federation of Red Cross and Red Crescent Societies (IFRC)',
  'Médecins Sans Frontières (MSF)',
  'World Wildlife Fund (WWF)',
  'United States Geological Survey (USGS)',
  'European Centre for Disease Prevention and Control (ECDC)',
  'Interpol',
  'International Labour Organization (ILO)',
  'International Energy Agency (IEA)',
  'World Economic Forum (WEF)',
  'Union of Concerned Scientists (UCS)',
  'Environmental Protection Agency (EPA)',
  'International Atomic Energy Agency (IAEA)',
  'Food and Agriculture Organization (FAO)',
  'Save the Children',
  'Oxfam',
  'Plan International',
  'International Rescue Committee (IRC)',
  'ReliefWeb',
  'Doctors of the World',
  'International Organization for Migration (IOM)',
  'Environmental Defense Fund (EDF)',
  'Natural Resources Defense Council (NRDC)',
  'International Union for Conservation of Nature (IUCN)',
  'UNICEF',
  'Habitat for Humanity',
  'CARE International',
  'WaterAid',
  'Save the Children',
  'World Vision',
  'Transparency International',
  'RAND Corporation',
  'Carnegie Endowment for International Peace',
  'Brookings Institution',
  'Council on Foreign Relations (CFR)',
  'Royal United Services Institute (RUSI)',
  'Institute for Strategic Studies (IISS)',
  'European Council on Foreign Relations (ECFR)',
  'Clingendael Institute',
  'Wilton Park',
  'Center for Strategic and International Studies (CSIS)',
]

const bbcApiSorces = [
  'BBC Journalists and Reporters',
  'BBC World Service',
  'Press Association',
  'Associated Press (AP)',
  'Reuters',
  'Agence France-Presse (AFP)',
  'BBC Monitoring',
  'Digital Look',
  'BBC Sport',
  'BBC Specialist Units',
  'BBC Correspondents Worldwide',
  'Non-BBC Journalists',
  'National News Agencies',
  'Freelance Writers',
  'Press Releases',
  'Think Tanks',
  'Research Institutions',
  'Government Reports',
  'Eyewitness Accounts',
  'User-Generated Content',
  'Multimedia Content Providers',
  'Academic Journals',
  'Scientific Research',
  'Public Records and Documents',
  'Non-Governmental Organizations (NGOs)',
  'International Organizations',
  'Public Opinion Polls',
  'Social Media Platforms',
  'Local News Outlets',
  'Investigative Journalism Networks',
  'ReliefWeb',
  'Human Rights Watch',
  'Amnesty International',
  'Transparency International',
  'International Crisis Group',
  'Greenpeace',
  'World Health Organization (WHO)',
  'United Nations (UN)',
  'International Monetary Fund (IMF)',
  'World Bank',
  'OECD (Organization for Economic Co-operation and Development)',
  'Pew Research Center',
  'Gallup',
  'Ipsos',
  'YouGov',
  'Center for Disease Control and Prevention (CDC)',
  'NASA',
  'European Space Agency (ESA)',
  'International Federation of Red Cross and Red Crescent Societies (IFRC)',
  'Médecins Sans Frontières (MSF)',
  'World Wildlife Fund (WWF)',
]

const nytApiCategories = [
  'Business',
  'Climate',
  'Education',
  'Corrections',
  'Crosswords & Games',
  'Dining',
  'Editor’s Picks',
  'Equity & Inclusion',
  'Health',
  'Home & Garden',
  'Jobs',
  'Leadership',
  'Media',
  'Parenting',
  'Podcasts',
  'Reader Center',
  'Style',
  'The Learning Network',
  'Times Insider',
  'Travel',
  'Wirecutter',
  'Book Review',
  'Real Estate',
  'Science',
  'Theater',
  'Upshot',
]

const newsApiCategories = [
  'Arts',
  'Books',
  'Business',
  'Cities',
  'Climate Crisis',
  'Culture',
  'Fashion',
  'Food',
  'Health',
  'Lifestyle',
  'Opinion',
  'Politics',
  'Society',
  'Sport',
  'Technology',
  'Travel',
  'US News',
  'World News',
  'Media',
  'Film',
  'Music',
  'Television & Radio',
]

const guardianApiCategories = [
  'Africa',
  'Asia',
  'Australia',
  'Europe',
  'Latin America',
  'Middle East',
  'US & Canada',
  'World',
  'Business',
  'Politics',
  'Health',
  'Education',
  'Science',
  'Technology',
  'Entertainment & Arts',
  'Coronavirus Pandemic',
  'Climate',
  'Weather',
  'In Pictures',
  'Reality Check',
]

const bbcApiCategories = [
  'Top Headlines',
  'Latest News',
  'Breaking News',
  'Global',
  'Local',
  'Business',
  'Entertainment',
  'Health',
  'Science',
  'Sports',
  'Technology',
  'Weather',
  'Opinion',
  'Lifestyle',
]

export {
  nytApiAuthors,
  nytApiCategories,
  nytApiSources,
  bbcApiAuthors,
  bbcApiCategories,
  bbcApiSorces,
  guardianApiAuthors,
  guardianApiSources,
  guardianApiCategories,
  newsApiAuthors,
  newsApiSources,
  newsApiCategories,
}
