const nytApiAuthors = [
  'A. G. Sulzberger',
  'Meredith Kopit Levien',
  'Joseph Kahn',
  'Kathleen Kingsbury',
  'William Bardeen',
  'Diane Brayton',
  'Rebecca Grossman-Cohen',
  'Alex Hardiman',
  'Marc Lacey',
  'David Perpich',
  'Joy Robins',
  'David Rubin',
  'Carolyn Ryan',
  'Jason Sobel',
  'Jacqueline M. Welch',
  'Hannah Yang',
  'Crystal Arroyo',
  'Dean Baquet',
  'Michael Barbaro',
  'Brooks Barnes',
  'Ellen Barry',
  'Dan Barry',
  'Katie Barry Ishibashi',
  'Anna Bialas',
  'Jane Blackburn Bornemeier',
  'Michael Brown',
  'Mark Bulik',
  'Audra Burch',
  'Claudio Cabrera',
  'Veronica Chambers',
  'Lian Chang',
  'Cynara Charles-Pierre',
  'Jason Chen',
  'Philip B. Corbett',
  'Pamela Della Motta',
  'Monica Drake',
  'Stephen Dunbar-Johnson',
  'John Eligon',
  'Matthew Ericson',
  'Manny Fernandez',
  'Mara Gay',
  'Peter S. Goodman',
  'Dana Green',
  'Guy Griggs',
  'Jessica Grose',
  'Holly Harnisch',
  'Charo Henríquez',
  'Mike Isaac',
  'Jordan Jacobson',
  'Susan Justus',
  'Chanelle Kalfas',
  'Jennifer Kanjana',
  'Kwame Opam',
  'Rich Lowry',
  'Emily Weinstein',
  'Chris Azzopardi',
  'Shreeya Sinha',
  'Anderson Tepper',
  'John Branch',
  'Jodi Kantor',
  'Megan Twohey',
  'Nicholas Kristof',
  'Maggie Haberman',
  'David Brooks',
  'Paul Krugman',
  'Thomas Friedman',
  'Maureen Dowd',
  'Frank Bruni',
  'Charles M. Blow',
  'Andrew Ross Sorkin',
  'Cecilia Kang',
  'Carl Hulse',
  'David Leonhardt',
  'Donald G. McNeil Jr.',
  'Sheryl Gay Stolberg',
  'Lisa Lerer',
  'Peter Baker',
  'Michael D. Shear',
  'Adam Goldman',
  'Katie Benner',
  'Catie Edmondson',
  'Emily Cochrane',
  'Jim Rutenberg',
  'Rukmini Callimachi',
  'Alan Rappeport',
  'Eric Lipton',
  'Miriam Jordan',
  'Rachel L. Swarns',
  'Frances Robles',
  'Astead W. Herndon',
  'Michael Crowley',
  'Jennifer Steinhauer',
  'Shane Goldmacher',
  'Thomas Kaplan',
  'Luke Broadwater',
  'Sheryl Gay Stolberg',
]

const guardianApiAuthors = [
  'George Monbiot',
  'Jonathan Freedland',
  'Marina Hyde',
  'Owen Jones',
  'Polly Toynbee',
  'Simon Jenkins',
  'Zoe Williams',
  'Gary Younge',
  'Aditya Chakrabortty',
  'John Crace',
  'Gaby Hinsliff',
  'Seumas Milne',
  'Hadley Freeman',
  'Patrick Wintour',
  'Larry Elliott',
  'Carole Cadwalladr',
  'Nick Cohen',
  'Peter Walker',
  'Jessica Elgot',
  'Rafael Behr',
  'Andrew Rawnsley',
  'Michael Savage',
  'Rowena Mason',
  'Heather Stewart',
  'Dan Sabbagh',
  'Julian Borger',
  'Jason Burke',
  'Haroon Siddique',
  'Kevin Rawlinson',
  'Matthew Weaver',
  'Jamie Grierson',
  'Damien Gayle',
  'Mark Townsend',
  "Lisa O'Carroll",
  'Jennifer Rankin',
  'Daniel Boffey',
  'Jon Henley',
  'Angelique Chrisafis',
  'Kim Willsher',
  'Sam Jones',
  'Ashifa Kassam',
  'Tom Phillips',
  'Dom Phillips',
  'Jonathan Watts',
  'Oliver Holmes',
  'Bethan McKernan',
  'Martin Chulov',
  'Patrick Kingsley',
  'Ruth Michaelson',
  'Michael Safi',
  'Helen Davidson',
  'Ben Doherty',
  'Kate Lyons',
  'Hannah Ellis-Petersen',
  'Rebecca Ratcliffe',
  'Lily Kuo',
  'Emma Graham-Harrison',
  'Jason Rodrigues',
  'David Pegg',
  'Rob Evans',
  'Paul Lewis',
  'David Conn',
  'Amelia Gentleman',
  'Frances Perraudin',
  'Nazia Parveen',
  'Josh Halliday',
  'Helen Pidd',
  'Jessica Murray',
  'Maya Wolfe-Robinson',
  'Alexandra Topping',
  'Harriet Sherwood',
  'Harriet Grant',
  'Diane Taylor',
  'Jamie Doward',
  'Mark Sweney',
  'Jim Waterson',
  'Archie Bland',
  'Esther Addley',
  'Caroline Davies',
  'Steven Morris',
  'Steven McCaffery',
  'Henry McDonald',
  'Sarah Boseley',
  'Ian Sample',
  'Damian Carrington',
  'Nicola Davis',
  'Hannah Devlin',
  'Robin McKie',
  'Fiona Harvey',
  'Patrick Barkham',
  'Phoebe Weston',
  'Arthur Neslen',
  'Jonathan Liew',
  'Suzanne Wrack',
  'Paul MacInnes',
  'Ben Fisher',
  'Greg Wood',
  'John Brewin',
  'Louise Taylor',
  'Ed Aarons',
  'Jacob Steinberg',
  'Barry Glendenning',
  'Marcela Mora y Araujo',
  'Tom Dart',
  'Sid Lowe',
  'Nick Ames',
  'David Hytner',
  'Stuart James',
  'Daniel Harris',
  'Will Unwin',
  'Scott Murray',
  'Rob Smyth',
  'Simon Burnton',
  'Tim de Lisle',
]

const bbcApiAuthors = [
  'Clive Myrie',
  'Sophie Raworth',
  'Reeta Chakrabarti',
  'Jane Hill',
  'Anna Foster',
  'Ben Brown',
  'Fiona Bruce',
  'Mishal Husain',
  'Tina Daheley',
  'Victoria Derbyshire',
  'Faisal Islam',
  'Jon Kay',
  'Sally Nugent',
  'Naga Munchetty',
  'Charlie Stayt',
  'Roger Johnson',
  'Ben Thompson',
  'Rachel Burden',
  'Nina Warhurst',
  'Kasia Madera',
  'Matthew Amroliwala',
  'Martine Croxall',
  'Julian Worricker',
  "Jane O'Brien",
  'Karin Giannone',
  'Geeta Guru-Murthy',
  'Shaun Ley',
  'Annita McVeigh',
  'Lewis Vaughan Jones',
  'Cathy Newman',
  'Justin Webb',
  'Huw Edwards',
  'John Simpson',
  'Orla Guerin',
  'Laura Kuenssberg',
  'Katty Kay',
  'Lyse Doucet',
  'Sophie Long',
  'Lucy Hockings',
  'Razwan Ullah',
  'Tom Brook',
  'Nick Bryant',
  'David Eades',
  'Duncan Golestani',
  'Clive Myrie',
  'Lebohang Mojapelo',
  'Yalda Hakim',
  'Suhaiymah Manzoor-Khan',
  'Kirsty Wark',
  'Stephen Sackur',
  'Carrie Gracie',
  'Mark Urban',
  'Kirsty Lang',
  'Maxine Mawhinney',
  'Anita Anand',
  'Zeina Khodr',
  'Lyse Doucet',
  'Gabriel Gatehouse',
  'Jeremy Bowen',
  'Kevin Connolly',
  'Mark Lowen',
  'Robin Brant',
  'Katty Kay',
]

const newsApiAuthors = [
  'John Doe',
  'Jane Smith',
  'Michael Johnson',
  'Emily Davis',
  'David Brown',
  'Sarah Wilson',
  'Chris Lee',
  'Jessica Taylor',
  'Daniel Martinez',
  'Laura Anderson',
  'Samantha White',
  'Andrew Moore',
  'Rachel Clark',
  'Steven Miller',
  'Megan Thompson',
  'James King',
  'Anna Scott',
  'Benjamin Young',
  'Linda Harris',
  'Richard Hall',
  'Amy Adams',
  'Matthew Turner',
  'Sophia Evans',
  'Brian Wright',
  'Olivia Harris',
  'Ethan Rodriguez',
  'Ava Bennett',
  'Mason Ross',
  'Charlotte Walker',
  'Elijah Mitchell',
  'Amelia Thompson',
  'Lucas Rivera',
  'Harper Campbell',
  'Jackson Parker',
  'Isabella Nelson',
  'Alexander Hughes',
  'Mia Foster',
  'Michael Gray',
  'Emma Russell',
  'Liam Hayes',
  'Sophia Ward',
  'Noah Peterson',
  'Emily Brooks',
  'James Reed',
  'Aiden Sanders',
  'Logan Baker',
  'Evelyn Cooper',
]

const nytApiSources = [
  'The New York Times',
  'International Herald Tribune',
  'New York Times Blogs',
  'NYTimes.com',
  'The New York Times Magazine',
  'The New York Times Book Review',
  'Reuters',
  'Associated Press',
  'UPI',
  'Agence France-Presse',
  'Bloomberg',
  'ProPublica',
  'CNBC',
  'CNN',
  'BBC News',
  'NPR',
  'PBS NewsHour',
  'The Guardian',
  'The Washington Post',
  'The Wall Street Journal',
  'Time',
  'USA Today',
  'Newsweek',
  'Business Insider',
  'Politico',
  'The Atlantic',
  'The Economist',
  'Financial Times',
  'The Telegraph',
  'The Independent',
  'Ars Technica',
  'TechCrunch',
  'Mashable',
  'Vox',
  'BuzzFeed',
  'Engadget',
  'Wired',
  'The Verge',
  'National Geographic',
  'Scientific American',
  'Nature',
  'Medical News Today',
  'Forbes',
  'Fox News',
  'Al Jazeera English',
  'Sky News',
  'Sky Sports',
  'ESPN',
  'Fox Sports',
  'CBS News',
  'NBC News',
  'ABC News',
  'Huffington Post',
  'Salon',
  'Electrek',
  'Digital Trends',
  'SlashGear',
  'TechRadar',
  'ZDNet',
  "Barron's",
  'WSOC-TV',
  'WSOC-TV Charlotte',
  'Axios',
  'BBC Sport',
  'The Sun',
  'The Daily Mail',
  'The Mirror',
  'Metro',
  'Scientific American',
  'Popular Science',
  'Live Science',
  'Discover Magazine',
  'ScienceDaily',
  'Nature News',
  'Smithsonian Magazine',
  'Space.com',
  'New Scientist',
  'Astronomy Magazine',
  'MIT Technology Review',
  'Wired Science',
  'The Hollywood Reporter',
  'Variety',
  'Deadline',
  'Billboard',
  'Rolling Stone',
  'NME',
  'Vulture',
  'Entertainment Weekly',
  'People',
  'Vanity Fair',
  'GQ',
  'Esquire',
  "Men's Health",
  "Women's Health",
  'Health',
  'WebMD',
  'Psychology Today',
  'The Scientist',
  'New York Post',
  'The Toronto Star',
  'The Globe and Mail',
  'The Australian',
  'The Sydney Morning Herald',
  'South China Morning Post',
  'The Straits Times',
  'The Japan Times',
  'The Times of India',
]

const newsApiSources = [
  'ABC News',
  'Al Jazeera English',
  'Associated Press',
  "Barron's",
  'BBC News',
  'Bloomberg',
  'Business Insider',
  'BuzzFeed',
  'CBS News',
  'CNN',
  'CNET',
  'Electrek',
  'Engadget',
  'Financial Times',
  'Forbes',
  'Fox News',
  'Huffington Post',
  'Karen Martin',
  'Mashable',
  'Medical News Today',
  'National Geographic',
  'Nature',
  'NBC News',
  'New York Magazine',
  'NPR',
  'Politico',
  'Reuters',
  'Salon',
  'Scientific American',
  'TechCrunch',
  'The Guardian',
  'The Independent',
  'The New York Times',
  'The Telegraph',
  'The Times of India',
  'The Wall Street Journal',
  'The Washington Post',
  'Time',
  'TipRanks',
  'USA Today',
  'Vox',
  'Wired',
  'WSOC-TV',
  'WSOC-TV Charlotte',
  'Axios',
  'BBC Sport',
  'ESPN',
  'Fox Sports',
  'Sky News',
  'Sky Sports',
  'The Sun',
  'The Daily Mail',
  'The Mirror',
  'Metro',
  'The Verge',
  'Ars Technica',
  'Digital Trends',
  'SlashGear',
  'TechRadar',
  'ZDNet',
]

const guardianApiSources = [
  'Journalists and Reporters',
  'News Agencies',
  'Freelance Writers',
  'Public Records and Documents',
  'Interviews and Eyewitness Accounts',
  'Research and Studies',
  'User-Generated Content',
  'Press Releases',
  'Think Tanks and NGOs',
  'Scientific Journals',
  'Books and Literature',
  'Public Records and Databases',
  'Partnerships',
  'Opinion Pieces and Columns',
  'Data Journalism',
  'Crowdsourcing',
  'Foreign Correspondents',
  'Multimedia Content',
  'Investigative Reports',
  'Reuters',
  'Associated Press (AP)',
  'Agence France-Presse (AFP)',
  'Bloomberg',
  'Press Association (PA)',
  'Al Jazeera',
  'Thomson Reuters Foundation',
  'Xinhua News Agency',
  'TASS (Russian News Agency)',
  'Kyodo News',
  'The New York Times',
  'BBC News',
  'CNN',
  'Financial Times',
  'The Washington Post',
  'NPR (National Public Radio)',
  'The Independent',
  'The Economist',
  'VICE News',
  'Deutsche Welle (DW)',
  'South China Morning Post',
  'Le Monde',
  'El País',
  'HuffPost',
  'BuzzFeed News',
  'Politico',
  'The Wall Street Journal',
  'The Times',
  'The Telegraph',
  'Forbes',
  'TIME Magazine',
  'USA Today',
  'Los Angeles Times',
  'The Atlantic',
  'Slate',
  'New York Magazine',
  'The Nation',
  'Mother Jones',
  'ProPublica',
  'The Intercept',
  'CBC News',
  'CTV News',
  'ABC News',
  'Sky News',
  'Channel 4 News',
  'The Sydney Morning Herald',
  'Global Voices',
  'The Conversation',
  'Reporters Without Borders (RSF)',
  'Human Rights Watch',
  'Amnesty International',
  'Transparency International',
  'International Crisis Group',
  'Greenpeace',
  'World Health Organization (WHO)',
  'United Nations (UN)',
  'International Monetary Fund (IMF)',
  'World Bank',
  'OECD (Organization for Economic Co-operation and Development)',
  'Pew Research Center',
  'Gallup',
  'Ipsos',
  'YouGov',
  'Center for Disease Control and Prevention (CDC)',
  'NASA',
  'European Space Agency (ESA)',
  'International Federation of Red Cross and Red Crescent Societies (IFRC)',
  'Médecins Sans Frontières (MSF)',
  'World Wildlife Fund (WWF)',
  'United States Geological Survey (USGS)',
  'European Centre for Disease Prevention and Control (ECDC)',
  'Interpol',
  'International Labour Organization (ILO)',
  'International Energy Agency (IEA)',
  'World Economic Forum (WEF)',
  'Union of Concerned Scientists (UCS)',
  'Environmental Protection Agency (EPA)',
  'International Atomic Energy Agency (IAEA)',
  'Food and Agriculture Organization (FAO)',
  'Save the Children',
  'Oxfam',
  'Plan International',
  'International Rescue Committee (IRC)',
  'ReliefWeb',
  'Doctors of the World',
  'International Organization for Migration (IOM)',
  'Environmental Defense Fund (EDF)',
  'Natural Resources Defense Council (NRDC)',
  'International Union for Conservation of Nature (IUCN)',
  'UNICEF',
  'Habitat for Humanity',
  'CARE International',
  'WaterAid',
  'Save the Children',
  'World Vision',
  'Transparency International',
  'RAND Corporation',
  'Carnegie Endowment for International Peace',
  'Brookings Institution',
  'Council on Foreign Relations (CFR)',
  'Royal United Services Institute (RUSI)',
  'Institute for Strategic Studies (IISS)',
  'European Council on Foreign Relations (ECFR)',
  'Clingendael Institute',
  'Wilton Park',
  'Center for Strategic and International Studies (CSIS)',
]

const bbcApiSorces = [
  'BBC Journalists and Reporters',
  'BBC World Service',
  'Press Association',
  'Associated Press (AP)',
  'Reuters',
  'Agence France-Presse (AFP)',
  'BBC Monitoring',
  'Digital Look',
  'BBC Sport',
  'BBC Specialist Units',
  'BBC Correspondents Worldwide',
  'Non-BBC Journalists',
  'National News Agencies',
  'Freelance Writers',
  'Press Releases',
  'Think Tanks',
  'Research Institutions',
  'Government Reports',
  'Eyewitness Accounts',
  'User-Generated Content',
  'Multimedia Content Providers',
  'Academic Journals',
  'Scientific Research',
  'Public Records and Documents',
  'Non-Governmental Organizations (NGOs)',
  'International Organizations',
  'Public Opinion Polls',
  'Social Media Platforms',
  'Local News Outlets',
  'Investigative Journalism Networks',
  'ReliefWeb',
  'Human Rights Watch',
  'Amnesty International',
  'Transparency International',
  'International Crisis Group',
  'Greenpeace',
  'World Health Organization (WHO)',
  'United Nations (UN)',
  'International Monetary Fund (IMF)',
  'World Bank',
  'OECD (Organization for Economic Co-operation and Development)',
  'Pew Research Center',
  'Gallup',
  'Ipsos',
  'YouGov',
  'Center for Disease Control and Prevention (CDC)',
  'NASA',
  'European Space Agency (ESA)',
  'International Federation of Red Cross and Red Crescent Societies (IFRC)',
  'Médecins Sans Frontières (MSF)',
  'World Wildlife Fund (WWF)',
]

const nytApiCategories = [
  'Business',
  'Climate',
  'Education',
  'Corrections',
  'Crosswords & Games',
  'Dining',
  'Editor’s Picks',
  'Equity & Inclusion',
  'Health',
  'Home & Garden',
  'Jobs',
  'Leadership',
  'Media',
  'Parenting',
  'Podcasts',
  'Reader Center',
  'Style',
  'The Learning Network',
  'Times Insider',
  'Travel',
  'Wirecutter',
  'Book Review',
  'Real Estate',
  'Science',
  'Theater',
  'Upshot',
]

const newsApiCategories = [
  'Arts',
  'Books',
  'Business',
  'Cities',
  'Climate Crisis',
  'Culture',
  'Fashion',
  'Food',
  'Health',
  'Lifestyle',
  'Opinion',
  'Politics',
  'Society',
  'Sport',
  'Technology',
  'Travel',
  'US News',
  'World News',
  'Media',
  'Film',
  'Music',
  'Television & Radio',
]

const guardianApiCategories = [
  'Africa',
  'Asia',
  'Australia',
  'Europe',
  'Latin America',
  'Middle East',
  'US & Canada',
  'World',
  'Business',
  'Politics',
  'Health',
  'Education',
  'Science',
  'Technology',
  'Entertainment & Arts',
  'Coronavirus Pandemic',
  'Climate',
  'Weather',
  'In Pictures',
  'Reality Check',
]

const bbcApiCategories = [
  'Top Headlines',
  'Latest News',
  'Breaking News',
  'Global',
  'Local',
  'Business',
  'Entertainment',
  'Health',
  'Science',
  'Sports',
  'Technology',
  'Weather',
  'Opinion',
  'Lifestyle',
]

export {
  nytApiAuthors,
  nytApiCategories,
  nytApiSources,
  bbcApiAuthors,
  bbcApiCategories,
  bbcApiSorces,
  guardianApiAuthors,
  guardianApiSources,
  guardianApiCategories,
  newsApiAuthors,
  newsApiSources,
  newsApiCategories,
}
